// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/replayer": {
    params: {};
  };
  "/garage": {
    params: {};
  };
  "/strategy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/replayer" | "/garage" | "/strategy";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/replayer.tsx": {
    id: "routes/replayer";
    page: "/replayer";
  };
  "routes/garage.tsx": {
    id: "routes/garage";
    page: "/garage";
  };
  "routes/strategy.tsx": {
    id: "routes/strategy";
    page: "/strategy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/replayer": typeof import("./app/routes/replayer.tsx");
  "routes/garage": typeof import("./app/routes/garage.tsx");
  "routes/strategy": typeof import("./app/routes/strategy.tsx");
};